#!/bin/bash

java -Dlog4j.configuration=file:$HOME/log4j.properties \
     -Dopflow.configuration=file:$HOME/worker.properties \
     -jar target/opflow-java-sample-worker.jar $@

#java -Dlog4j.configuration=file:$HOME/projects/opflow/opflow-java-sample/worker/src/main/resources/log4j.properties \
#     -Dopflow.configuration=file:$HOME/projects/opflow/opflow-java-sample/worker/src/main/resources/worker.properties \
#     -jar target/opflow-java-sample-worker.jar $@